class IOHandler{
    +startUI(): void
    -recieveUserInput(scanner: Scanner): void
    -createOrder(scanner: Scanner): boolean
    -emailReport(scanner: Scanner): boolean
    -displayAdminData(): void
    -finishSinging(scanner: Scanner): void
    -getMusicianByID(ID: int): MusicClubMember
    -getMusicianBySong(song: String): MusicClubMember
}

class MusicClubMember{
    -ID: int
    -song: String
    -isSinging: boolean
    -isDone: boolean
    -Name: String
    +startSinging(): void
    +finishSinging(): void
}

class Order{
    -email: String
    -sweetheartName: String
    -song: String
    -creditNum: String
    +ChargeCustomer(): void
}

IOHandler -d->"*" MusicClubMember
IOHandler -d->"*" Order

note top of IOHandler: While initially we planned to pass the input of the scanner into each function\nwe decided instead to pass in the scanner so that each function can ask its own\nquestions and recieve its own inputs